#!/bin/bash

LC_CTYPE=en_US.utf8

i="$1"
filename="$2"
query="$3"

getname () {
 echo "$1" | pup '.gs_ri .gs_rt a text{}' | tr -d '\n' | sed -e 's/\( \)*/\1/g'
}

getsummary () {
 echo "$1" | pup '.gs_ri .gs_rs text{}' | tr -d '\n' | sed -e 's/\( \)*/\1/g'
}

getid () {
 echo "$1" | pup '.gs_ri .gs_rt a attr{id}'
}

geturl () {
 echo "$1" | pup '.gs_ri .gs_rt a attr{href}'
}

getauth () {
    echo "$1" | pup --charset utf8 '.gs_ri .gs_a text{}' | paste -sd "" | sed -e 's/\( \)*/\1/g'
}

getauthors () {
    #echo "$1" | pup --charset utf8 '.gs_ri .gs_a text{}' | paste -sd "" | cut -d "-" -f 1 | tr -d '\n'
    getauth "$1" | awk -F" - " '{print $1}'
}

getvenue () {
    #echo "$1" | pup '.gs_ri .gs_a text{}' | tr "\n" " " | cut -d "-" -f 2 | tr -d '\n' | cut -d "," -f 1
    getauth "$1" | awk -F" - " '{print $2}' | cut -d "," -f 1
}

getyear () {
    getauth "$1" | awk -F" - " '{print $2}' | grep -m 1 -oP "[1-2][0-9][0-9][0-9]" | head -1
}

getpublisher () {
   getauth "$1" | awk -F" - " '{print $3}' 
}

getcited () {
 echo "$1" | pup '.gs_ri .gs_fl a:contains("Cited") text{}' | grep -oP "\d+"
}

html=$(cat "$filename" | pup  ".gs_r[data-rp=\"$i\"]" | sed -e 's/\xe2\x80\xa6/.../g' | sed -e 's/\xc2\xa0/ /g' | sed -e 's/|/--/g' -e 's/\xe2\x80\x94/-/g')

#echo "$html"

echo $(getname "$html" )
echo $(getid "$html")
echo $(geturl "$html")
#echo $(getauth "$html")
echo $(getauthors "$html")
echo $(getvenue "$html")
echo $(getyear "$html")
echo $(getpublisher "$html")
echo $(getsummary "$html")
echo $(getcited "$html")
echo "$i"
echo $(date +"%F")
echo "$query"
